package com.lecafe.common.enums;

import java.util.HashMap;

public enum RecordType
{
    UNDEFINED( 0 ),
    AUTHENTICATE_USER( 1 ),
    RECOVER_PASSWORD( 2 ),
    CHANGE_PASSWORD( 3 ),
    UPDATE_LANGUAGE( 4 ),
    UPDATE_CONFIGURATION( 5 ),
    UPDATE_PROFILE_PICTURE( 6 ),
    REGISTER_MEDIC( 7 ),
    UPDATE_BASIC_PROFILE( 8 ),
    ADD_MEDIC_DOCUMENT( 9 ),
    DELETE_MEDIC_DOCUMENT( 10 ),
    ADD_MEDIC_EVENT( 11 ),
    UPDATE_MEDIC_EVENT( 12 ),
    DELETE_MEDIC_EVENT( 13 ),
    ADD_MEDIC_PAYMENT( 14 ),
    DELETE_MEDIC_PAYMENT( 15 ),
    UPDATE_MEDIC_PAYMENT( 16 ),
    ADD_MEDIC_SCHEDULES( 17 ),
    UPDATE_MEDIC_SCHEDULES( 18 ),
    DELETE_MEDIC_SCHEDULES( 19 ),
    PAY_MEDIC_MEMBERSHIP_STRIPE( 20 ),
    PAY_MEDIC_MEMBERSHIP_PAYPAL( 21 ),
    UPDATE_EMERGENCY_STATE( 22 ),
    REGISTER_PATIENT( 23 ),
    REGISTER_DEPENDENT_USER( 24 ),
    UPDATE_LAST_MODIFIED( 25 ),
    ADD_HABIT( 26 ),
    UPDATE_HABIT( 27 ),
    DELETE_HABIT( 28 ),
    ADD_ALLERGY( 29 ),
    UPDATE_ALLERGY( 30 ),
    DELETE_ALLERGY( 31 ),
    UPDATE_ALLERGY_ATTACHMENTS( 32 ),
    ADD_MEDICAL_CONDITION( 33 ),
    UPDATE_MEDICAL_CONDITION( 34 ),
    DELETE_MEDICAL_CONDITION( 35 ),
    UPDATE_MEDICAL_CONDITION_ATTACHMENTS( 36 ),
    ADD_MEDICAL_DEVICE( 37 ),
    UPDATE_MEDICAL_DEVICE( 38 ),
    DELETE_MEDICAL_DEVICE( 39 ),
    UPDATE_MEDICAL_DEVICE_ATTACHMENTS( 40 ),
    ADD_CONTACT( 41 ),
    UPDATE_CONTACT( 42 ),
    DELETE_CONTACT( 43 ),
    ADD_MEDICATION( 44 ),
    UPDATE_MEDICATION( 45 ),
    DELETE_MEDICATION( 46 ),
    UPDATE_MEDICATION_ATTACHMENTS( 47 ),
    ADD_FAMILY_BACKGROUND( 48 ),
    UPDATE_FAMILY_BACKGROUND( 49 ),
    DELETE_FAMILY_BACKGROUND( 50 ),
    UPDATE_FAMILY_BACKGROUND_ATTACHMENTS( 51 ),
    ADD_MEDICAL_INSURANCE( 52 ),
    UPDATE_MEDICAL_INSURANCE( 53 ),
    DELETE_MEDICAL_INSURANCE( 54 ),
    UPDATE_MEDICAL_INSURANCE_ATTACHMENTS( 55 ),
    RENEW_PIN( 56 ),
    DELETE_DEPENDENT_USER( 57 ),
    SEND_EMERGENCY_LOCATION( 58 ),
    UPDATE_EMERGENCY_LOCATION( 59 ),
    VERIFY_MEDICAL_RECORD( 60 ),
    ADD_PATIENT_FILE( 61 ),
    ADD_PATIENT_FILE_BY_MEDIC( 62 ),
    DELETE_PATIENT_FILE( 63 ),
    UPDATE_PATIENT_FILE( 64 ),
    UPDATE_PATIENT_FILE_VISIBILITY( 65 ),
    ADD_PATIENT_FOLDER_PERMISSION( 66 ),
    DELETE_PATIENT_FOLDER_PERMISSION( 67 ),
    CHANGE_DEPENDENT_USER( 68 ),
    CREATE_EMERGENCY( 69 ),
    CREATE_APPOINTMENT( 70 ),
    UPDATE_APPOINTMENT_STATUS( 71 ),
    CREATE_APPOINTMENT_HISTORY( 72 ),
    CREATE_MEDIC_QUALIFICATION( 73 ),
    CREATE_PATIENT_QUALIFICATION( 74 ),
    RESCHEDULE_APPOINTMENT_BY_MEDIC( 75 ),
    RESCHEDULE_APPOINTMENT_BY_PATIENT( 76 ),
    RESCHEDULE_APPOINTMENT_BY_ADMIN( 77 ),
    CREATE_EMERGENCY_PAY_STRIPE( 78 ),
    CREATE_EMERGENCY_PAY_PAYPAL( 79 ),
    PAY_APPOINTMENT_STRIPE( 80 ),
    PAY_APPOINTMENT_PAYPAL( 81 ),
    CANCEL_APPOINTMENT_MEDIC( 82 ),
    CANCEL_APPOINTMENT_ON_TIME_PATIENT( 83 ),
    CANCEL_APPOINTMENT_OUT_OF_TIME_PATIENT( 84 ),
    PATIENT_MARK_LOST_APPOINTMENT_BY_MEDIC( 85 ),
    MEDIC_MARK_LOST_APPOINTMENT_BY_PATIENT( 86 ),
    CANCEL_APPOINTMENT_ADMIN( 87 ),
    UPDATE_HISTORY_VISIBILITY( 88 ),
    UPDATE_MEDIC_FEES( 89 ),
    APPROVE_MEDIC( 90 ),
    REJECT_MEDIC( 91 ),
    PRE_CANCEL_MEDIC( 92 ),
    CANCEL_MEDIC( 93 ),
    REACTIVATE_MEDIC( 94 ),
    ACTIVATE_PATIENT( 95 ),
    BLOCK_PATIENT( 96 );

    private int _value;
    private static HashMap<Integer, RecordType> _map = new HashMap<>();

    RecordType(int value )
    {
        _value = value;
    }

    static
    {
        for( RecordType type : RecordType.values() )
        {
            _map.put( type._value, type );
        }
    }

    public static RecordType valueOf(int typeNum )
    {
        RecordType response = _map.get( typeNum );

        if( response == null )
            throw new IllegalArgumentException( "No enum constant was found for value: " + typeNum );

        return response;
    }

    public int getValue()
    {
        return _value;
    }
}
